name: visio_per_computador
channels:
  - defaults
dependencies:
  - conda=4.9.0
  - pip=20.2.4
  - python=3.6.12
  - tqdm=4.50.2
  - pip:
    - matplotlib==3.3.3
    - numpy==1.18.5
    - opencv-contrib-python==3.4.2.17
